### ISSUE TITLE
#TODO

### ISSUE THREAD

**Issue by AntoineBellemare** [osanas/jspsych_Pareidolia#1]
- [x] Add agree button 
- [x] Make images 60% of screen (they are too big now)
- [x] Add fixation cross for 0.5sec before image
- [x] Make the background during image presentation the same grey as the fixation cross background
- [x] Make the space for writing the 3 words larger
- [x] Ajuster largeur du texte pour instructions pareidolie
- [ ] Progress bar
- [ ] Validate that data is saved every image
- [x] Securiser API
- [x] Change layout of the 10 words filling screen, so we can see the 10 words at the same time (too much space now each filling space)
